---
name: Clippy

'on': [pull_request]

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Note: cargo fmt must always be run with nightly
      - name: toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          components: clippy, rustfmt

      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: cargo fmt
        run: |
          cargo +nightly fmt --all -- --check

      - name: Install cargo-lints
        run: |
          cargo install cargo-lints

      - name: Clippy check futures_async (with lints)
        run: |
          cargo lints clippy --all-targets --features futures_async

      - name: Clippy check tokio (with lints)
        run: |
          cargo lints clippy --all-targets --features tokio_async
